### ISSUE TITLE
ISO 20150424 fail to boot on some hardware

### ISSUE THREAD

**Issue by tnut** [NuTyX/saravane#1]
with following information
...
Looking in /sys/block/sda for media
Looking in /sys/block/sdb for media
mount: /dev/sdb is write-protected, mounting read-only
Looking in /sys/block/sr0 for media
...

Then nothing happens anymore

**Comment by bertux** [comment]
Je vais tester sur les machines que j'ai chez moi et peut-être même celles
que j'ai au bureau pour voir si j'arrive à reproduire le problème.

**Comment by tnut** [comment]
Merci Bertux

**Comment by tnut** [comment]
J'ai pu identifier la source du prob, reste à le résoudre. Il concerne Geantbrun ET Christophe

**Comment by tnut** [comment]
I beleave it's related https://github.com/gentoo/eudev/issues/114

**Comment by tnut** [comment]
Manquait les firmwares ... Maintenant ça ne bloque plus chez moi
