### ISSUE TITLE
Ajouter gvfs à la liste des paquets pour Xfce

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/saravane#35]
Un bug relativement "simple" à corriger. Il faudrait rajouter gvfs lors de l'installation de Xfce pour avoir un accès direct aux médias amovibles, du genre clé USB ou en DVD.

Ce serait mieux pour l'utilisateur, non ?

**Comment by FredBezies** [comment]
Au pire, rajouter une entrée dans la documentation générale de la distribution ? A moins qu'elle m'ait échappé ?

**Comment by tnut** [comment]
NuTyX étant une distribution mécano, chacun peut si il le souhaite l'option x y ou z. Pour ce qui est de gvfs c'est pour moi une option comme une autre que personnellement je n'utilise pas (dieu merci) car je ne suis pas interessé de voir mes 10 partitions s'afficher sur le bureau pour au finale ne pas pouvoir les monter automatiquement. Par contre oui là il y a un bug j'ourvre une nouvelle issue, merci de m'y avoir fait penser.
