### ISSUE TITLE
Ajouter xdg-user-dirs à tous les environnements.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/saravane#36]
Les outils xdg-user-dirs sont bien pratiques, car ils offrent l'accès direct aux répertoires Documents, Images, Modèles, Téléchargements, Vidéo et Public.

De plus, c'est un standard de freedesktop, reconnu par tous les environnements de bureaux.

Enfin, ce n'est pas un paquet énorme. Sur mon archlinux, le paquet xdg-user-dirs pèse...

````[fred@fredo-arch ~]$ pacman -Qi xdg-user-dirs | grep Taille````
````Taille installée : 146,00 KiB````

**Comment by tnut** [comment]
T'arrives à me mettre la recette grossomodo  (celle de arch par ex) ?

**Comment by FredBezies** [comment]
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xdg-user-dirs

Dépendances : docbook-xsl

Compilation : 

build() {
  cd $pkgname-$pkgver
  ./configure --prefix=/usr --sysconfdir=/etc
  make
}

Très lourd comme tu peux le constater.

**Comment by tnut** [comment]
Ajouté dans xfce 4.12.x
