### ISSUE TITLE
KDM qui se plaint du manque de la session lxde ?

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/saravane#38]
J'ai remarqué qu'au premier lancement d'un KDE fraichement installé, quand j'entre pour la première fois mon nom d'utilisateur et que j'appuie sur la touche tab pour accéder au champ du mot de passe, j'ai une gueulante.

KDM se plaint de l'absence d'une session lxde manquante. Cf la capture d'écran.

Une idée de la cause de ce bug ?

![bug-kdm](https://cloud.githubusercontent.com/assets/8571419/7666157/1fbbc3f4-fbda-11e4-80ec-de81d4b5846a.png)

**Comment by FredBezies** [comment]
Bien entendu on peut accéder à KDE sans problème par la suite.

**Comment by tnut** [comment]
C'est comique ça. Personnellement je créée toujours un utilisateur APRES l'install de l'environnement et donc ce prob n'appparaît pas. Je me tate pour garder ou non kde vu que je ne l'utilise plus (devient du portnawak) et que c'est vraiment à l'antipode de la phylosophie de NuTyX... Vais sans doute proposer lxde et ede (quand j'arriverai à un résultat potable)

**Comment by FredBezies** [comment]
J'ai créé l'utilisateur avant l'installation de l'environnement. Fausse manipulation de ma part donc ;)

**Comment by tnut** [comment]
Ce sera corrigé ds le prochain aaabasicfs
