### ISSUE TITLE
Plus d'accès au serveur

### ISSUE THREAD

**Issue by christophe60fr** [NuTyX/saravane#45]
Bonjour,

Depuis hier, un "check" ou un "get" plantent.
Je suppose que le souci vient de chez moi, mais je ne pense pas avoir fait quoi que ce soit de spécial.
Je n'ai plus non plus accès aux "Copies d'écrans et fonds d'écrans" du forum.

C'est quoi l'erreur ???

**Comment by tnut** [comment]
Nous sommes sans serveur de téléchargement depuis hier soir.

La durée de la panne n'étant pas encore déterminée, vous pouvez utilisez le serveur de secours:

http://downloads.tuxfamily.org/nutyx/

Dans votre fichier [b]/etc/cards.conf[/b], faites l'ajustement via édition ou via sed (si vous êtes actuellement sur downloads.nutyx.org

sed -i "s@downloads.nutyx.org@downloads.tuxfamily.org/nutyx@" /etc/cards.conf

**Comment by tnut** [comment]
Super bonne nouvelle, le serveur est déjà remis en service
