### ISSUE TITLE
Cards n'installe pas les binaires créés localement.

### ISSUE THREAD

**Issue by sh4d0w31410** [NuTyX/saravane#47]
Je rencontre des difficultés avec cards. Je suis parti d'une installation de base de nutyx. J'ai créé une chroot avec un scénario D, et créé tous les binaires de xfce4.12 dans /srv/www/saravane/personnel.
Dans la nutyx principale, j'ai ajouté la ligne dir /chroot/srv/www/saravane/personnel au début de /etc/cards.conf.
Dans la nutyx principale, si je fait cards info -p xfce4, elle voit mon xfce4.12, et cards info -b xfce4 voit xfce4.10.
Mais get xfce4 installe xfce 4.10 au lieu de 4.12.
Il est fort possible que j'ai mal configuré ma machine, pourtant j'ai tout vérifié.

**Comment by tnut** [comment]
Hmmm intéressant, j'essaie de reproduire

**Comment by tnut** [comment]
Peux-tu vérifier ton fichier pkgmk.conf ? Je crois que tu as du oublié les deux variables:

PKGMK_IGNORE_REPO="no"
PKGMK_IGNORE_COLLECTION="no"

**Comment by tnut** [comment]
Fonctionne parfaitement si le fichier pkgmk.conf est configuré correctement cad:
PKGMK_IGNORE_REPO="no"
PKGMK_IGNORE_COLLECTION="no"

**Comment by sh4d0w31410** [comment]
Bonjour tnut, désolé pour le retard..
En effet, bien configuré, cards fonctionne parfaitement!
Merci

**Comment by tnut** [comment]
:)
